menu:
  Home: /
  Archives: /archives
     
  # 关于我: /about
  # 文章归档: /archives
  # 有情链接: /links

excerpt_link: Read More ›

google_analytics: 

comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: euanchan
